<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Advent-of-Code-2021" data-toc-modified-id="Advent-of-Code-2021-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Advent of Code 2021</a></span><ul class="toc-item"><li><span><a href="#Reader-Function" data-toc-modified-id="Reader-Function-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Reader Function</a></span></li><li><span><a href="#Day-1" data-toc-modified-id="Day-1-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Day 1</a></span><ul class="toc-item"><li><span><a href="#Part-1" data-toc-modified-id="Part-1-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Part 1</a></span><ul class="toc-item"><li><span><a href="#Test" data-toc-modified-id="Test-1.2.1.1"><span class="toc-item-num">1.2.1.1&nbsp;&nbsp;</span>Test</a></span></li><li><span><a href="#Real-Data" data-toc-modified-id="Real-Data-1.2.1.2"><span class="toc-item-num">1.2.1.2&nbsp;&nbsp;</span>Real Data</a></span></li></ul></li><li><span><a href="#Part-2" data-toc-modified-id="Part-2-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>Part 2</a></span></li></ul></li><li><span><a href="#Day-2" data-toc-modified-id="Day-2-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Day 2</a></span><ul class="toc-item"><li><span><a href="#Part-1" data-toc-modified-id="Part-1-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>Part 1</a></span></li><li><span><a href="#Part-2" data-toc-modified-id="Part-2-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>Part 2</a></span></li></ul></li><li><span><a href="#Day-3" data-toc-modified-id="Day-3-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Day 3</a></span></li><li><span><a href="#Day-4" data-toc-modified-id="Day-4-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Day 4</a></span><ul class="toc-item"><li><span><a href="#Organized-Code" data-toc-modified-id="Organized-Code-1.5.1"><span class="toc-item-num">1.5.1&nbsp;&nbsp;</span>Organized Code</a></span></li></ul></li><li><span><a href="#Day-5" data-toc-modified-id="Day-5-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Day 5</a></span></li><li><span><a href="#Day-6" data-toc-modified-id="Day-6-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Day 6</a></span></li><li><span><a href="#Day-7" data-toc-modified-id="Day-7-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Day 7</a></span></li><li><span><a href="#Day-8" data-toc-modified-id="Day-8-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>Day 8</a></span></li><li><span><a href="#Day-9" data-toc-modified-id="Day-9-1.10"><span class="toc-item-num">1.10&nbsp;&nbsp;</span>Day 9</a></span></li><li><span><a href="#Day-10" data-toc-modified-id="Day-10-1.11"><span class="toc-item-num">1.11&nbsp;&nbsp;</span>Day 10</a></span></li><li><span><a href="#Day-11" data-toc-modified-id="Day-11-1.12"><span class="toc-item-num">1.12&nbsp;&nbsp;</span>Day 11</a></span></li><li><span><a href="#Day-12" data-toc-modified-id="Day-12-1.13"><span class="toc-item-num">1.13&nbsp;&nbsp;</span>Day 12</a></span></li><li><span><a href="#Day-13" data-toc-modified-id="Day-13-1.14"><span class="toc-item-num">1.14&nbsp;&nbsp;</span>Day 13</a></span></li><li><span><a href="#Day-14" data-toc-modified-id="Day-14-1.15"><span class="toc-item-num">1.15&nbsp;&nbsp;</span>Day 14</a></span></li><li><span><a href="#Day-15" data-toc-modified-id="Day-15-1.16"><span class="toc-item-num">1.16&nbsp;&nbsp;</span>Day 15</a></span></li><li><span><a href="#Day-16" data-toc-modified-id="Day-16-1.17"><span class="toc-item-num">1.17&nbsp;&nbsp;</span>Day 16</a></span></li><li><span><a href="#Day-17" data-toc-modified-id="Day-17-1.18"><span class="toc-item-num">1.18&nbsp;&nbsp;</span>Day 17</a></span></li><li><span><a href="#Day-18" data-toc-modified-id="Day-18-1.19"><span class="toc-item-num">1.19&nbsp;&nbsp;</span>Day 18</a></span></li><li><span><a href="#Day-19" data-toc-modified-id="Day-19-1.20"><span class="toc-item-num">1.20&nbsp;&nbsp;</span>Day 19</a></span></li><li><span><a href="#Day-20" data-toc-modified-id="Day-20-1.21"><span class="toc-item-num">1.21&nbsp;&nbsp;</span>Day 20</a></span></li><li><span><a href="#Day-21" data-toc-modified-id="Day-21-1.22"><span class="toc-item-num">1.22&nbsp;&nbsp;</span>Day 21</a></span></li><li><span><a href="#Day-22" data-toc-modified-id="Day-22-1.23"><span class="toc-item-num">1.23&nbsp;&nbsp;</span>Day 22</a></span></li><li><span><a href="#Day-23" data-toc-modified-id="Day-23-1.24"><span class="toc-item-num">1.24&nbsp;&nbsp;</span>Day 23</a></span></li><li><span><a href="#Day-24" data-toc-modified-id="Day-24-1.25"><span class="toc-item-num">1.25&nbsp;&nbsp;</span>Day 24</a></span></li><li><span><a href="#Day-25" data-toc-modified-id="Day-25-1.26"><span class="toc-item-num">1.26&nbsp;&nbsp;</span>Day 25</a></span></li></ul></li><li><span><a href="#Preparation-Section" data-toc-modified-id="Preparation-Section-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Preparation Section</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Push-Code" data-toc-modified-id="Push-Code-2.0.1"><span class="toc-item-num">2.0.1&nbsp;&nbsp;</span>Push Code</a></span></li></ul></li><li><span><a href="#Prepare-data-files-for-all-days" data-toc-modified-id="Prepare-data-files-for-all-days-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Prepare data files for all days</a></span></li></ul></li></ul></div>

# Advent of Code 2021

## Reader Function

In [1]:
def get_data(day=1):
    """
    Returns test and real data in list format.
    Raw data should be maintained as:
        [test data]
        Split From Here
        [actual data]
    """
    file_name = f"data/day{day}.txt"
    
    with open(file_name) as fp:
        data = fp.read().strip().split("Split From Here")
        data = [d.strip().split("\n") for d in data]
        return data
get_data()

[['199', '200', '208', '210', '200', '207', '240', '269', '260', '263'],
 ['171',
  '173',
  '174',
  '163',
  '161',
  '157',
  '156',
  '154',
  '152',
  '156',
  '151',
  '153',
  '132',
  '135',
  '151',
  '143',
  '141',
  '149',
  '145',
  '147',
  '142',
  '143',
  '139',
  '141',
  '144',
  '147',
  '137',
  '144',
  '147',
  '153',
  '151',
  '153',
  '157',
  '185',
  '186',
  '185',
  '181',
  '161',
  '177',
  '179',
  '177',
  '178',
  '173',
  '175',
  '183',
  '181',
  '191',
  '189',
  '186',
  '189',
  '192',
  '191',
  '189',
  '199',
  '208',
  '218',
  '216',
  '210',
  '209',
  '208',
  '215',
  '207',
  '198',
  '202',
  '204',
  '205',
  '204',
  '203',
  '205',
  '207',
  '208',
  '209',
  '218',
  '234',
  '231',
  '245',
  '244',
  '243',
  '265',
  '264',
  '279',
  '282',
  '283',
  '274',
  '276',
  '279',
  '281',
  '279',
  '258',
  '256',
  '289',
  '297',
  '300',
  '304',
  '308',
  '298',
  '302',
  '317',
  '316',
  '315',
  '314',
  '296',
  '298',


## Day 1

[Here is the link.](https://adventofcode.com/2021/day/1)

### Part 1

In [2]:
data,data1 = get_data() 
data = list(map(int, data))
data1 = list(map(int, data1))

data

[199, 200, 208, 210, 200, 207, 240, 269, 260, 263]

#### Test

In [3]:
pd = None
res = []
for d in data:
    if pd is None:
        res.append(None)
    else:
        if pd>d:
            res.append("0")
        else:
            res.append("1")
    pd=d

In [4]:
res.count("1")

7

#### Real Data

In [5]:
pd = None
res = []
for d in data1:
    if pd is None:
        res.append(None)
    else:
        if pd>d:
            res.append("0")
        else:
            res.append("1")
    pd=d
res.count("1")

1266

### Part 2

In [6]:
w = []
wsum = []
i = 0
ps = None
for j in range(3, len(data1)+1):
    wsum.append(sum(data1[i:j]))
    i+=1

pd = None
res1 = []
for d in wsum:
    if pd is None:
        res1.append(None)
    else:
        if pd>=d:
            res1.append("0")
        else:
            res1.append("1")
    pd=d


In [7]:
res1.count("1")

1217

## Day 2

In [8]:
data,data1 = get_data(day=2)

In [9]:
data

['forward 5', 'down 5', 'forward 8', 'up 3', 'down 8', 'forward 2']

### Part 1

In [10]:
hs = 0
vs = 0

for d in data:
    k,v = d.split()
    
    if k =="forward":
        hs+=int(v)
    elif k == "down":
        vs+=int(v)
    elif k=="up":
        vs-=int(v)
    
print(hs*vs)

150


In [11]:
hs = 0
vs = 0

for d in data1:
    k,v = d.split()
    
    if k =="forward":
        hs+=int(v)
    elif k == "down":
        vs+=int(v)
    elif k=="up":
        vs-=int(v)
    
print(hs*vs)

1947824


### Part 2

In [12]:
hs = 0
vs = 0
aim = 0

for d in data1:
    k,v = d.split()
    v = int(v)
    
    if k =="forward":
        hs+=v
        vs+=aim*v
    elif k == "down":
        aim+=v
#         vs+=v
    elif k=="up":
        aim-=v
#         vs-=v
    
print(hs*vs)

1813062561


## Day 3
[Here is the link.](https://adventofcode.com/2021/day/3)
    



In [3]:
from collections import Counter
import numpy as np
data,data1 = get_data(day=3)

In [15]:
data1

['010001110001',
 '110100000001',
 '111001001011',
 '111100001000',
 '000111101001',
 '101111001001',
 '111111000110',
 '000101110010',
 '001101001010',
 '000110001101',
 '011111111110',
 '101100010001',
 '110101100001',
 '000000000110',
 '010011000011',
 '010101110010',
 '011001001001',
 '010011010111',
 '001101010110',
 '100000101000',
 '011100110010',
 '001011110001',
 '101110110011',
 '100011011101',
 '000101111011',
 '000010011000',
 '110101101111',
 '011010101100',
 '111001011010',
 '011100110011',
 '000101000111',
 '111000110101',
 '110111010000',
 '111110010001',
 '010100100110',
 '010001011010',
 '101100100001',
 '001000101010',
 '011111010010',
 '101011100110',
 '100111010110',
 '101000110100',
 '011010110001',
 '000010001000',
 '100001110111',
 '101001011100',
 '100100001011',
 '111010101110',
 '001101101001',
 '000111111100',
 '011011111000',
 '111111111011',
 '101100011010',
 '011101001001',
 '111001001000',
 '010101010001',
 '100000011011',
 '100110100011',
 '010101110111

In [20]:
def part1(inp):
    cs = len(inp[0])
    dt = [int(d) for dt in inp for d in dt]
    dt = np.array(dt).reshape(-1, cs)

    print(dt[0])

    # sorted(x.items(), key=lambda item: item[1])
    counts = [sorted(dict(Counter(dt[:, i])).items(), key=lambda item: item[1]) for i in range(len(dt[0]))]
    counts = np.array(counts).reshape(-1,2)

#     print(counts)

    minidx = np.arange(0, len(counts), 2)
    maxidx = np.arange(1, len(counts), 2)

    minv = int("".join(list(map(str, counts[minidx, 0]))), 2)
    maxv = int("".join(list(map(str, counts[maxidx, 0]))), 2)
    print(minv, maxv)
    print(minv*maxv)
part1(data)

[0 0 1 0 0]
9 22
198


In [21]:
part1(data1)

[0 1 0 0 0 1 1 1 0 0 0 1]
1749 2346
4103154


In [55]:
def o2(dt):
    ndt = dt.copy()
    #print(len(ndt[0]))
    
    curr_c = 0
    while curr_c<len(dt[0]):
        print(f"Current Col: {curr_c}")
        counts = [sorted(dict(Counter(ndt[:, curr_c])).items(), key=lambda item: item[1])]
        counts = np.array(counts).reshape(-1,2)
        if len(counts)>1:
            if counts[0, 1]==counts[1, 1]:
                ndt = ndt[ndt[:,curr_c]==1]
            else:
                ndt = ndt[ndt[:,curr_c]==counts[1][0]]
        else:
            ndt = ndt[ndt[:,curr_c]==counts[1][0]]
        print(f"Current Col: {curr_c} Rows: {len(ndt)}")
#         print(counts)
#         print(ndt[ndt[:,curr_c]==counts[1][0]])
            
        
        
        curr_c+=1
    res = int("".join(list(map(str, ndt[0]))), 2)
    print(res)
    return res

def co2(dt):
    ndt = dt.copy()
    #print(len(ndt[0]))
    
    curr_c = 0
    while curr_c<len(dt[0]):
        
        counts = [sorted(dict(Counter(ndt[:, curr_c])).items(), key=lambda item: item[1])]
        counts = np.array(counts).reshape(-1,2)
        if len(counts)>1:
            if counts[0, 1]== counts[1, 1]:
                ndt = ndt[ndt[:,curr_c]==0]
            else:
                ndt = ndt[ndt[:,curr_c]==counts[0][0]]
        else:
            ndt = ndt[ndt[:,curr_c]==counts[0][0]]
            
#         print(ndt)
        print(f"Current Col: {curr_c} Rows: {len(ndt)}")
        curr_c+=1
    return int("".join(list(map(str, ndt[0]))), 2)

def part2(inp):
    cs = len(inp[0])
    dt = [int(d) for dt in inp for d in dt]
    dt = np.array(dt).reshape(-1, cs)
    
    print("O2")
    o2v = o2(dt)
    co2v = co2(dt)
    print(o2v, co2v)
    print(o2v*co2v)
part2(data)
    

O2
Current Col: 0
Current Col: 0 Rows: 7
Current Col: 1
Current Col: 1 Rows: 4
Current Col: 2
Current Col: 2 Rows: 3
Current Col: 3
Current Col: 3 Rows: 2
Current Col: 4
Current Col: 4 Rows: 1
23
Current Col: 0 Rows: 5
Current Col: 1 Rows: 2
Current Col: 2 Rows: 1
Current Col: 3 Rows: 1
Current Col: 4 Rows: 1
23 10
230


In [56]:
part2(data1)

O2
Current Col: 0
Current Col: 0 Rows: 511
Current Col: 1
Current Col: 1 Rows: 263
Current Col: 2
Current Col: 2 Rows: 134
Current Col: 3
Current Col: 3 Rows: 71
Current Col: 4
Current Col: 4 Rows: 36
Current Col: 5
Current Col: 5 Rows: 20
Current Col: 6
Current Col: 6 Rows: 12
Current Col: 7
Current Col: 7 Rows: 8
Current Col: 8
Current Col: 8 Rows: 5
Current Col: 9
Current Col: 9 Rows: 3
Current Col: 10
Current Col: 10 Rows: 2
Current Col: 11
Current Col: 11 Rows: 1
3399
Current Col: 0 Rows: 489
Current Col: 1 Rows: 235
Current Col: 2 Rows: 109
Current Col: 3 Rows: 54
Current Col: 4 Rows: 24
Current Col: 5 Rows: 11
Current Col: 6 Rows: 4
Current Col: 7 Rows: 2
Current Col: 8 Rows: 1
Current Col: 9 Rows: 1
Current Col: 10 Rows: 1
Current Col: 11 Rows: 1
3399 1249
4245351


## Day 4

[Here is the link.](https://adventofcode.com/2021/day/4)


In [2]:
import numpy as np
data,data1 = get_data(day=4)

In [3]:
data

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1',
 '',
 '22 13 17 11  0',
 ' 8  2 23  4 24',
 '21  9 14 16  7',
 ' 6 10  3 18  5',
 ' 1 12 20 15 19',
 '',
 ' 3 15  0  2 22',
 ' 9 18 13 17  5',
 '19  8  7 25 23',
 '20 11 10 24  4',
 '14 21 16 12  6',
 '',
 '14 21 17 24  4',
 '10 16 15  9 19',
 '18  8 23 26 20',
 '22 11 13  6  5',
 ' 2  0 12  3  7']

In [21]:
block = []
num = [int(i) for i in data[0].split(",")]
row = []
tdata=[]
blocks = 0

for d in data[2:]:
#     print(d)
    if d == "":
        tdata.append(block)
        block=[]
        blocks+=1
        
    else:
#         print([i for i in d.strip().split(" ") if i!=""])
        block.append([int(i) for i in d.strip().split(" ") if i!=""])
tdata.append(block)
block=[]
blocks+=1
print(blocks)

3


In [ ]:
tdata = np.array(tdata).reshape(blocks,-1, 5)
tdata

In [23]:
results = np.zeros_like(tdata).astype(np.bool)
matched = False
for n in num:
#     print(n)
    for i,block in enumerate(tdata):
        results[i] += block==n
#         print(results[i])
        
        # search across row
        if (results[i]==[ True,  True,  True,  True,  True]).all(axis=1).any():
            print(f"Row Matched Block:{i}")
            matched=True
            break
        
        # search across cols
        if (results[i].T==[ True,  True,  True,  True,  True]).all(axis=1).any():
            print(f"Col Matched Block: {i}")
            matched=True
            break
    if matched:
#         print(i)
#         print(tdata[i])
        s = (tdata[i]*~results[i]).sum()
        print(s)
        print(n)
        print(n*s)
        break
        
        

Row Matched Block:2
188
24
4512


In [31]:
block = []
num = [int(i) for i in data1[0].split(",")]
row = []
tdata=[]
blocks = 0

for d in data1[2:]:
#     print(d)
    if d == "":
        tdata.append(block)
        block=[]
        blocks+=1
        
    else:
#         print([i for i in d.strip().split(" ") if i!=""])
        block.append([int(i) for i in d.strip().split(" ") if i!=""])
tdata.append(block)
block=[]
blocks+=1
print(blocks)

tdata = np.array(tdata).reshape(blocks,-1, 5)
tdata

results = np.zeros_like(tdata).astype(np.bool)
matched = False
mblocks=[]
all_blocks = list(range(0, blocks))
# print(all_blocks)
for n in num:
#     print(n)
    for i,block in enumerate(tdata):
        results[i] += block==n
#         print(results[i])
        
        # search across row
        if (results[i]==[ True,  True,  True,  True,  True]).all(axis=1).any():
            print(f"Row Matched Block:{i}")
            if i not in mblocks:
                mblocks.append(i)
            if len(mblocks) == len(all_blocks):
                matched=True
            
#             break
        
        # search across cols
        if (results[i].T==[ True,  True,  True,  True,  True]).all(axis=1).any():
            print(f"Col Matched Block: {i}")
            if i not in mblocks:
                mblocks.append(i)
            if len(mblocks) == len(all_blocks):
                matched=True
            
#             break
    if matched:
        i = mblocks[i]
        
        print(tdata[i])
        s = (tdata[i]*~results[i]).sum()
        print(s)
        print(n)
        print(n*s)
        break
        
        

100
Row Matched Block:73
Row Matched Block:73
Row Matched Block:73
Row Matched Block:73
Row Matched Block:73
Col Matched Block: 57
Row Matched Block:73
Col Matched Block: 57
Row Matched Block:73
Row Matched Block:79
Col Matched Block: 33
Col Matched Block: 57
Row Matched Block:73
Row Matched Block:79
Col Matched Block: 33
Col Matched Block: 57
Row Matched Block:73
Row Matched Block:79
Col Matched Block: 33
Col Matched Block: 57
Row Matched Block:73
Row Matched Block:79
Col Matched Block: 29
Col Matched Block: 33
Col Matched Block: 57
Row Matched Block:73
Row Matched Block:79
Col Matched Block: 29
Col Matched Block: 33
Col Matched Block: 57
Row Matched Block:73
Row Matched Block:79
Row Matched Block:94
Col Matched Block: 29
Col Matched Block: 33
Col Matched Block: 57
Row Matched Block:73
Row Matched Block:79
Row Matched Block:94
Row Matched Block:23
Col Matched Block: 29
Col Matched Block: 33
Col Matched Block: 57
Col Matched Block: 60
Col Matched Block: 70
Row Matched Block:73
Row Matc

Row Matched Block:30
Row Matched Block:32
Row Matched Block:33
Col Matched Block: 33
Col Matched Block: 35
Row Matched Block:36
Col Matched Block: 38
Col Matched Block: 39
Col Matched Block: 40
Row Matched Block:41
Row Matched Block:43
Col Matched Block: 43
Row Matched Block:44
Col Matched Block: 44
Row Matched Block:46
Col Matched Block: 48
Row Matched Block:49
Col Matched Block: 50
Row Matched Block:51
Row Matched Block:53
Col Matched Block: 56
Row Matched Block:57
Col Matched Block: 57
Row Matched Block:59
Col Matched Block: 59
Row Matched Block:60
Col Matched Block: 60
Row Matched Block:61
Col Matched Block: 61
Col Matched Block: 64
Row Matched Block:66
Row Matched Block:67
Row Matched Block:70
Col Matched Block: 70
Col Matched Block: 71
Row Matched Block:72
Row Matched Block:73
Row Matched Block:74
Col Matched Block: 77
Row Matched Block:78
Row Matched Block:79
Col Matched Block: 79
Row Matched Block:80
Row Matched Block:81
Col Matched Block: 81
Row Matched Block:82
Row Matched Bl

Row Matched Block:96
Col Matched Block: 97
Col Matched Block: 98
Col Matched Block: 99
Row Matched Block:0
Row Matched Block:1
Row Matched Block:2
Col Matched Block: 2
Row Matched Block:3
Col Matched Block: 3
Col Matched Block: 6
Col Matched Block: 7
Row Matched Block:8
Row Matched Block:9
Col Matched Block: 9
Row Matched Block:12
Col Matched Block: 12
Row Matched Block:13
Col Matched Block: 13
Row Matched Block:14
Col Matched Block: 14
Row Matched Block:15
Col Matched Block: 15
Row Matched Block:16
Col Matched Block: 16
Row Matched Block:17
Col Matched Block: 17
Col Matched Block: 19
Row Matched Block:20
Col Matched Block: 20
Col Matched Block: 21
Col Matched Block: 22
Row Matched Block:23
Col Matched Block: 23
Row Matched Block:24
Col Matched Block: 24
Row Matched Block:26
Col Matched Block: 26
Row Matched Block:27
Col Matched Block: 27
Row Matched Block:28
Col Matched Block: 28
Row Matched Block:29
Col Matched Block: 29
Row Matched Block:30
Row Matched Block:32
Col Matched Block: 32

Col Matched Block: 86
Row Matched Block:87
Col Matched Block: 87
Row Matched Block:88
Col Matched Block: 88
Row Matched Block:89
Col Matched Block: 89
Row Matched Block:90
Col Matched Block: 90
Row Matched Block:91
Col Matched Block: 91
Row Matched Block:93
Col Matched Block: 93
Row Matched Block:94
Col Matched Block: 94
Row Matched Block:96
Row Matched Block:97
Col Matched Block: 97
Col Matched Block: 98
Row Matched Block:99
Col Matched Block: 99
Row Matched Block:0
Row Matched Block:1
Col Matched Block: 1
Row Matched Block:2
Col Matched Block: 2
Row Matched Block:3
Col Matched Block: 3
Row Matched Block:4
Row Matched Block:5
Col Matched Block: 5
Row Matched Block:6
Col Matched Block: 6
Row Matched Block:7
Col Matched Block: 7
Row Matched Block:8
Col Matched Block: 8
Row Matched Block:9
Col Matched Block: 9
Row Matched Block:12
Col Matched Block: 12
Row Matched Block:13
Col Matched Block: 13
Row Matched Block:14
Col Matched Block: 14
Row Matched Block:15
Col Matched Block: 15
Row Matc

Col Matched Block: 20
Col Matched Block: 21
Col Matched Block: 22
Row Matched Block:23
Col Matched Block: 23
Row Matched Block:24
Col Matched Block: 24
Row Matched Block:25
Row Matched Block:26
Col Matched Block: 26
Row Matched Block:27
Col Matched Block: 27
Row Matched Block:28
Col Matched Block: 28
Row Matched Block:29
Col Matched Block: 29
Row Matched Block:30
Col Matched Block: 30
Row Matched Block:31
Col Matched Block: 31
Row Matched Block:32
Col Matched Block: 32
Row Matched Block:33
Col Matched Block: 33
Col Matched Block: 34
Row Matched Block:35
Col Matched Block: 35
Row Matched Block:36
Col Matched Block: 36
Row Matched Block:37
Col Matched Block: 37
Row Matched Block:38
Col Matched Block: 38
Col Matched Block: 39
Row Matched Block:40
Col Matched Block: 40
Row Matched Block:41
Col Matched Block: 41
Row Matched Block:42
Col Matched Block: 42
Row Matched Block:43
Col Matched Block: 43
Row Matched Block:44
Col Matched Block: 44
Row Matched Block:45
Col Matched Block: 45
Row Match

Row Matched Block:23
Col Matched Block: 23
Row Matched Block:24
Col Matched Block: 24
Row Matched Block:25
Col Matched Block: 25
Row Matched Block:26
Col Matched Block: 26
Row Matched Block:27
Col Matched Block: 27
Row Matched Block:28
Col Matched Block: 28
Row Matched Block:29
Col Matched Block: 29
Row Matched Block:30
Col Matched Block: 30
Row Matched Block:31
Col Matched Block: 31
Row Matched Block:32
Col Matched Block: 32
Row Matched Block:33
Col Matched Block: 33
Col Matched Block: 34
Row Matched Block:35
Col Matched Block: 35
Row Matched Block:36
Col Matched Block: 36
Row Matched Block:37
Col Matched Block: 37
Row Matched Block:38
Col Matched Block: 38
Row Matched Block:39
Col Matched Block: 39
Row Matched Block:40
Col Matched Block: 40
Row Matched Block:41
Col Matched Block: 41
Row Matched Block:42
Col Matched Block: 42
Row Matched Block:43
Col Matched Block: 43
Row Matched Block:44
Col Matched Block: 44
Row Matched Block:45
Col Matched Block: 45
Row Matched Block:46
Col Matched

Col Matched Block: 97
Row Matched Block:98
Col Matched Block: 98
Row Matched Block:99
Col Matched Block: 99
[[85 64 44 39 57]
 [90 30 15 35 54]
 [78 89 55 99 12]
 [80 96 20 50 45]
 [56 10 71 59 17]]
246
20
4920


### Organized Code

In [ ]:
def get_blocks(dt):
    block = []
    num = [int(i) for i in dt[0].split(",")]
    row = []
    tdata=[]
    blocks = 0
    for d in dt[2:]:
        if d == "":
            tdata.append(block)
            block=[]
            blocks+=1

        else:
            block.append([int(i) for i in d.strip().split(" ") if i!=""])
    tdata.append(block)
    block=[]
    blocks+=1
    tdata = np.array(tdata).reshape(blocks,-1, 5)
    return tdata, num

def get_first_matched(tdata, num):
    results = np.zeros_like(tdata).astype(np.bool)
    matched = False
    
    for n in num:
        for i,block in enumerate(tdata):
            results[i] += block==n
            # search across row
            if (results[i]==[ True,  True,  True,  True,  True]).all(axis=1).any():
                print(f"Row Matched Block:{i}")
                matched=True
                break

            # search across cols
            if (results[i].T==[ True,  True,  True,  True,  True]).all(axis=1).any():
                print(f"Col Matched Block: {i}")
                matched=True
                break
        if matched:
            print(f"\nResult Block: {tdata[i]}")
            s = (tdata[i]*~results[i]).sum()
            print(f"Sum: {s}")
            print(f"Last number: {n}")
            print(f"Answer: {n*s}\n")
            break

def get_last_matched(tdata, num):
    results = np.zeros_like(tdata).astype(np.bool)
    matched = False
    mblocks=[]
    all_blocks = list(range(0, len(results)))
    
    for n in num:
        for i,block in enumerate(tdata):
            results[i] += block==n
            # search across row
            if (results[i]==[ True,  True,  True,  True,  True]).all(axis=1).any():
                print(f"Row Matched Block:{i}")
                if i not in mblocks:
                    mblocks.append(i)
                if len(mblocks) == len(all_blocks):
                    matched=True

            # search across cols
            if (results[i].T==[ True,  True,  True,  True,  True]).all(axis=1).any():
                print(f"Col Matched Block: {i}")
                if i not in mblocks:
                    mblocks.append(i)
                if len(mblocks) == len(all_blocks):
                    matched=True

        if matched:
            i = mblocks[i]

            print(f"\nResult Block: {tdata[i]}")
            s = (tdata[i]*~results[i]).sum()
            print(f"Sum: {s}")
            print(f"Last number: {n}")
            print(f"Answer: {n*s}")
            break

d1,n1 = get_blocks(data1)
get_first_matched(tdata=d1, num=n1)
get_last_matched(tdata=d1, num=n1)
# d1, n1

## Day 5

[Here is the link.](https://adventofcode.com/2021/day/5)




In [2]:
import numpy as np

data,data1 = get_data(day=5)

In [3]:
data

['0,9 -> 5,9',
 '8,0 -> 0,8',
 '9,4 -> 3,4',
 '2,2 -> 2,1',
 '7,0 -> 7,4',
 '6,4 -> 2,0',
 '0,9 -> 2,9',
 '3,4 -> 1,4',
 '0,0 -> 8,8',
 '5,5 -> 8,2']

In [4]:
# get (x1, y1), (x2, y2)
coordinates = []
for d in data1:
    x1, y1, x2, y2 = d.replace(" -> ", ",").split(",")
    coordinates.append((x1, y1, x2, y2))
coordinates = np.array(coordinates).astype(np.uint8)


In [5]:
coordinates

array([[ 87,  19,  87,  32],
       [179, 136, 179, 233],
       [  0, 202,   0, 187],
       ...,
       [ 83,  97, 239,  97],
       [ 46,  73,  46, 105],
       [212, 183, 173, 183]], dtype=uint8)

In [6]:
# get (x1, y1), (x2, y2)
coordinates = []
for d in data1:
    x1, y1, x2, y2 = list(map(int, d.replace(" -> ", ",").split(",")))
    coordinates.append((x1, y1, x2, y2))
    
coordinates = np.array(coordinates)

mxx,mxy = coordinates[[0, 2]].max(), coordinates[[1, 3]].max()

board = np.zeros((mxx*2, mxy*2))

# check only horizontal or vertical line
m1 = coordinates[:, 0]==coordinates[:, 2]
m2 = coordinates[:, 1]==coordinates[:, 3]
m = m1 | m2

masked = coordinates[m]

for co in masked:    
    for x in range(min(co[0], co[2]), max(co[0], co[2])+1):
        for y in range(min(co[1], co[3]), max(co[1], co[3])+1):
            board[x, y] += 1
(board.flatten()>1).sum()

7644

In [15]:
coordinates = []
for d in data1:
    x1, y1, x2, y2 = list(map(int, d.replace(" -> ", ",").split(",")))
    coordinates.append((x1, y1, x2, y2))
    
coordinates = np.array(coordinates)

mxx,mxy = coordinates[[0, 2]].max(), coordinates[[1, 3]].max()

board = np.zeros((mxx*2, mxy*2))

# check only horizontal or vertical line
m1 = coordinates[:, 0]==coordinates[:, 2]
m2 = coordinates[:, 1]==coordinates[:, 3]
m = m1 | m2

masked = coordinates[m]

for co in masked:    
    for x in range(min(co[0], co[2]), max(co[0], co[2])+1):
        for y in range(min(co[1], co[3]), max(co[1], co[3])+1):
            board[x, y] += 1
print((board.flatten()>1).sum())

# diagonal line
m1 = coordinates[:, 0]!=coordinates[:, 2]
m2 = coordinates[:, 1]!=coordinates[:, 3]
m=m1*m2
masked = coordinates[m]

for co in masked:
    # add or sub to x1?
    dx = int(co[2]>co[0]) or -1
    dy = int(co[3]>co[1]) or -1
    
    for dp in range(abs(co[2]-co[0])+1):
        x = co[0]+dx*dp
        y = co[1]+dy*dp
        board[x,y]+=1
        
print((board.flatten()>1).sum())

7644


18627

## Day 6

[Here is the link.](https://adventofcode.com/2021/day/6)




## Day 7

[Here is the link.](https://adventofcode.com/2021/day/7)




## Day 8

[Here is the link.](https://adventofcode.com/2021/day/8)




## Day 9

[Here is the link.](https://adventofcode.com/2021/day/9)




## Day 10

[Here is the link.](https://adventofcode.com/2021/day/10)




## Day 11

[Here is the link.](https://adventofcode.com/2021/day/11)




## Day 12

[Here is the link.](https://adventofcode.com/2021/day/12)



## Day 13

[Here is the link.](https://adventofcode.com/2021/day/13)




## Day 14

[Here is the link.](https://adventofcode.com/2021/day/14)




## Day 15

[Here is the link.](https://adventofcode.com/2021/day/15)




## Day 16

[Here is the link.](https://adventofcode.com/2021/day/16)




## Day 17

[Here is the link.](https://adventofcode.com/2021/day/17)




## Day 18

[Here is the link.](https://adventofcode.com/2021/day/18)




## Day 19

[Here is the link.](https://adventofcode.com/2021/day/19)




## Day 20

[Here is the link.](https://adventofcode.com/2021/day/20)




## Day 21

[Here is the link.](https://adventofcode.com/2021/day/21)




## Day 22

[Here is the link.](https://adventofcode.com/2021/day/22)




## Day 23

[Here is the link.](https://adventofcode.com/2021/day/23)




## Day 24

[Here is the link.](https://adventofcode.com/2021/day/24)




## Day 25

[Here is the link.](https://adventofcode.com/2021/day/25)


# Preparation Section

### Push Code

In [10]:
! git add .
! git commit -m "solved day4"
! git push origin master

The file will have its original line endings in your working directory
The file will have its original line endings in your working directory


[master 4369d36] solved day4
 2 files changed, 6095 insertions(+), 95 deletions(-)
 rewrite 2021/data/day4.txt (100%)


To https://github.com/q-viper/Adevent-Of-Code.git
   459ffe9..4369d36  master -> master


## Prepare data files for all days

In [41]:
for i in range(2, 26):
    with open(f"data/day{i}.txt","w") as fp:
        fp.writelines("Split From Here")
    

In [13]:

for i in range(4, 26):
    p = f"""
    ## Day {i}
    [Here is the problem link.](https://adventofcode.com/2021/day/{i})
    
    ### Part 1
    ```python
    
    ```
    
    ### Part 2
    ```python
    
    ```
    """
    print(p)


    ## Day 4
    [Here is the problem link.](https://adventofcode.com/2021/day/4)
    
    ### Part 1
    ```python
    
    ```
    
    ### Part 2
    ```python
    
    ```
    

    ## Day 5
    [Here is the problem link.](https://adventofcode.com/2021/day/5)
    
    ### Part 1
    ```python
    
    ```
    
    ### Part 2
    ```python
    
    ```
    

    ## Day 6
    [Here is the problem link.](https://adventofcode.com/2021/day/6)
    
    ### Part 1
    ```python
    
    ```
    
    ### Part 2
    ```python
    
    ```
    

    ## Day 7
    [Here is the problem link.](https://adventofcode.com/2021/day/7)
    
    ### Part 1
    ```python
    
    ```
    
    ### Part 2
    ```python
    
    ```
    

    ## Day 8
    [Here is the problem link.](https://adventofcode.com/2021/day/8)
    
    ### Part 1
    ```python
    
    ```
    
    ### Part 2
    ```python
    
    ```
    

    ## Day 9
    [Here is the problem link.](https://adventofcode.com/2021/day/9)
    
  